---

- hosts: all
  gather_facts: false
  tasks:
    - name: install python and deps for ansible modules
      raw: yum install -y libselinux-python

- hosts: all
  tasks:
    - name: install python2-dnf on Fedora
      raw: yum install -y python2-dnf
      when: "ansible_distribution == 'Fedora'"

    - name: install mc
      package: name=mc state=present

- hosts: all
  vars:
    epel_testing_enabled: 1
  roles:
    - { role: goozbach.EPEL, when: "ansible_distribution != 'Fedora'" }

- include: site_koji_postgresql.yml
- include: site_koji.yml
