---

- hosts: koji
  roles:
    - patrik.uytterhoeven.PostgreSQL-For-RHEL6x
    - koji-db
    - koji-ca
    - koji-hub

- hosts: koji_web
  roles:
    - koji-web

- hosts: koji_builder
  roles:
    - koji-builder
    - koji-kojira
