---

- hosts: all
  tasks:
    - debug: var={{ item }}
      with_items:
        - koji_package
        - koji_hub_package
        - koji_web_package
        - koji_builder_package
        - koji_kojira_package

- include: site_koji_client.yml
- include: site_koji_db.yml
- include: site_koji_ca.yml

- hosts:
    - koji_hub
    - koji_builder
  tasks:
    - name: install latest createrepo package
      package:
        name: createrepo
        state: latest

- include: site_koji_hub.yml
- include: site_koji_builder.yml
- include: site_koji_web.yml
- include: site_koji_mash.yml
