---

- hosts: all
  gather_facts: false
  tasks:
    - name: install python and deps for ansible modules
      raw: yum install -y libselinux-python
    # - yum: name=mc state=present

- hosts: all
  roles:
    - goozbach.EPEL

- include: site_koji.yml
