---

- hosts: all
  gather_facts: false
  tasks:
    - name: install python and deps for ansible modules
      raw: yum install -y libselinux-python
    # - yum: name=mc state=present

- hosts: all
  tasks:
    - name: install python2-dnf on Fedora
      raw: yum install -y python2-dnf
      when: "ansible_distribution == 'Fedora'"

- hosts: all
  roles:
    - { role: goozbach.EPEL, when: "ansible_distribution != 'Fedora'" }

- include: site_koji.yml
